export {
  GitWorkspaceError,
  GitWorkspaceManager,
  classifyProtectedPath,
  decodeProtectedPathPolicyExtension,
  isExplicitGitSha,
  normalizeAuthorizedScopes,
  normalizeCandidatePolicy,
  parseProtectedPathPolicyExtension,
  type CandidatePolicy,
  type CandidateVerification,
  type NormalizedCandidatePolicy,
  type ProtectedPathPolicyExtensionV1,
  type RelaxableProtectedPathClass,
  type BrokerCommitExpectation,
  type BrokerCommitMutationGuard,
  type BrokerCommitRecord,
  type ChangedPath,
  type EnsureMirrorInput,
  type OpenExistingMirrorInput,
  type FactoryMirror,
  type FactoryWorkspaceRecord,
  type GitWorkspaceManagerOptions,
  type AdvancedImmutableMirrorBinding,
  type ImmutableMirrorBinding,
  type ImmutableMirrorBindingTip,
  type PrepareImmutableMirrorInput,
} from "./workspace.js";
