export {
  GitWorkspaceError,
  GitWorkspaceManager,
  classifyProtectedPath,
  isExplicitGitSha,
  normalizeAuthorizedScopes,
  normalizeCandidatePolicy,
  type CandidatePolicy,
  type CandidateVerification,
  type NormalizedCandidatePolicy,
  type BrokerCommitExpectation,
  type BrokerCommitMutationGuard,
  type BrokerCommitRecord,
  type ChangedPath,
  type EnsureMirrorInput,
  type FactoryMirror,
  type FactoryWorkspaceRecord,
  type GitWorkspaceManagerOptions,
  type ImmutableMirrorBinding,
  type PrepareImmutableMirrorInput,
} from "./workspace.js";
